#!/bin/bash

export PYENV_VIRTUALENV_DISABLE_PROMPT=true
export PYENV_ROOT="${HOME}/.pyenv"
export PATH="${HOME}/.pyenv/bin:${PATH}"

function omg_prompt_callback {
    if [ -n "${VIRTUAL_ENV}" ]; then
        ENV_NAME=$(basename "${VIRTUAL_ENV}")
        echo "%F{white}(${ENV_NAME})%f "
    fi
}

antigen bundles <<EOBUNDLES
    pip
    pyenv
    django
EOBUNDLES

eval "$(pyenv init -)"
